# THIS IS AN EXAMPLE ON HOW YOU SHOULD CONFIGURE YOUR hugo.toml
# See this hugo.toml in action at https://github.com/1bl4z3r/hermit-V2/blob/staging/hugo.toml
# Example Site is Staging branch, acessible at https://github.com/1bl4z3r/hermit-V2/tree/staging
# To see what each config does, refer to https://1bl4z3r.github.io/hermit-V2/en/posts/explaining-configs/
# Open Issue or Pull Request at https://github.com/1bl4z3r/hermit-V2

baseURL = ""
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
theme = "hermit-v2"

[languages]
  [languages.en]
    title = 'covert_czar'
    [languages.en.params]
      homeSubtitle = "BCA student coding from a dark corner"
    weight = 1
 
 
languageCode = "en-us"

# title = "CHANGE ME"
# enableGitInfo = true

pygmentsCodefences  = true
pygmentsUseClasses  = true
#hasCJKLanguage = true

rssLimit = 10

copyright = "cc-by-nc-sa"
enableEmoji = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]


[params.author]
  name = "covert czar"
  about = "CHANGE SITE AUTHOR ABOUT"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.
  # category = "categories"

# Enable to get proper Mathjax support
#[markup]
#  [markup.goldmark]
#    [markup.goldmark.extensions]
#      [markup.goldmark.extensions.passthrough]
#        enable = true
#        [markup.goldmark.extensions.passthrough.delimiters]
#          block = [['\[', '\]'], ['$$', '$$']]
#          inline = [['\(', '\)']]


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # description = "CHANGE ME SITE DESCRIPTION"
  # images = [""]
  themeColor = "#494f5c"

  #homeSubtitle = "CHANGE ME HOME SUBTITLE"
  footerCopyright = "CC-BY-NC-SA"
  # bgImg = ""
  # gitUrl = "https://github.com/1bl4z3r/hermit-V2/tree/staging"

  justifyContent = false

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true 
  global_mathjax = false
  readTime = true
  readTimeSeparator = "CHANGE ME READ TIME"
  # legacyLayout = false
  shareSocial = true
  # googleTagManager = "GTM-XXXXXXXX"
  # tagSymbol = "#"
  # categorySymbol = "⊲"
  # pinned = "Pinned Posts"
  # pinnedSVGname = "pin"
  # descriptionInPosts= true
  # initialPublish = "Initally Posted on: "
  # human = ["single","posts"]
  
  [[params.socialLinks]]
    name = "mastodon"
    url = "https://mstdn.social/@covert_czar"

  [[params.socialLinks]]
    name = "x"
    url = "https://x.com/covert_czar/"

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/covertczar/"
    
      [[params.socialLinks]]
    name = "telegram"
    url = "https://t.me/covert_czar/"

  [[params.socialLinks]]
    name = "pixelfed"
    url = "https://pixelfed.social/Covert_czar"

 [[params.socialLinks]]
    name = "gitlab"
    url = "https://gitlab.com/covertczar"
    
     [[params.socialLinks]]
    name = "instagram"
    url = "https://www.instagram.com/covert_czar/"

    [[params.socialLinks]]
    name = "xmpp"
    url = "https://join.jabber.network/#covert_czar@macaw.me"
    
     [[params.socialLinks]]
    name = "matrix"
    url = "https://matrix.to/#/@covert_czar:matrix.org"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "https://text.tchncs.de/czars-blogs/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about-hugo/"
    weight = 20
